version: '3.4'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAGIE_API_KEY=${RAGIE_API_KEY}
      - DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}
    restart: unless-stopped
