post http://127.0.0.1:8000/api/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZGQ2MDU2MC1lOTBmLTQ1OTYtOTFlMS03NDVkODRmZTRjMWYiLCJ1bmlxdWVfbmFtZSI6Ikhhcm9sZCBCYXJ0b2xvIiwiSWRDb21wYW55IjoiZmJjYTY3ZDMtZTJjZi00NzVmLWJhNjgtY2FmMjQzY2Q5ZDBiIiwianRpIjoiNjFkZTNhN2EtOWRmNi00YTI2LWJiM2UtNGM0OTExNWFjN2M5IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTAwOTU0MjUsImlzcyI6IlNwb3RwbGFuIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MjMyIn0.qQo27kJWaBSPzUPpvG1VKAnhgYE-__dn7-oj0ZNYw2A

{
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "text": "Hi",
          "type": "text"
        }
      ]
    }
  ]
}